### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by maxitimes** [johnmcraig/Azure-image-gallery#2]
Had fun working with this Image Gallery and Azure, do you know when you might add the search and page numbering? 

Thank you

**Comment by johnmcraig** [comment]
Hello, thanks for the interest in this project. Right now all I can say is "Soon". I do not have a time frame when the features can be implemented. Currently working on another project and once it's finished I can return to this one.

**Comment by johnmcraig** [comment]
I know it's been nearly 3 years if there's still interest, but pagination and searching by title features have been implemented as of today - February 11th, 2021. Just as an FYI.
